defaults: &defaults

  # sites hosts
  # session expire seconds
  # admin role account
  # URL_HOST: 192.169.153.139:3000
  URL_HOST: localhost:3000
  URL_SCHEMA: http
  SESSION_EXPIRE: "60"
  ADMIN: 'admin@myexchangepea.dev,admin@example.com,ugwuc@hotmail.com'
  TIMEZONE: 'Beijing'

  REDIS_URL: redis://127.0.0.1:6379

  # below settings only in production env
  # system notify mail settings
  # --------------------------------------------------------------
  SMTP_PORT: 587
  # SMTP_AUTHENTICATION: "login" # could be plain, login or cram_md5
  SMTP_DOMAIN: bullxchange.io
  SMTP_ADDRESS: smtp.mailgun.org
  SMTP_USERNAME: postmaster@bullxchange.io
  SMTP_PASSWORD: af624dfcf6cc44a7517536c71f98fd6f
  SMTP_AUTHENTICATION: plain

  SUPPORT_MAIL: ugwuc@hotmail.com
  SYSTEM_MAIL_FROM: ugwuc@hotmail.com
  SYSTEM_MAIL_TO: ugwuc@hotmail.com
  OPERATE_MAIL_TO: ugwuc@hotmail.com

  # WebSocket Streaming API settings
  # --------------------------------------------------------------
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: 8080
  # Uncomment below to enable secure WebSocket (wss)
  #WEBSOCKET_SSL_KEY: 'your_server.key'
  #WEBSOCKET_SSL_CERT: 'your_server.crt'

  # pusher settings
  # --------------------------------------------------------------
  # myexchangepea dependence Pusher (http://pusher.com) service
  # you can change your key for production environment.
  # we support development key and secret
  # uncomment below line only development or test
  #
  # PUSHER_APP: 65910
  # PUSHER_KEY: 50d404c35db92d736a57
  # PUSHER_SECRET: 75d6e6685209cc60cc4d

  PUSHER_APP: 456480
  PUSHER_KEY: cac7cfcdeec4c7bd5096
  PUSHER_SECRET: c1bf3999d667a163b899
  PUSHER_HOST: api.pusherapp.com
  PUSHER_PORT: 80
  PUSHER_WS_PORT: 80
  PUSHER_WSS_PORT: 443
  PUSHER_ENCRYPTED: true
  # PUSHER_APP: 250172
  # PUSHER_KEY: c2dc225e0c94dc284206
  # PUSHER_SECRET: 823488f184dbaa08e483
  # PUSHER_HOST: api.pusherapp.com
  # PUSHER_PORT: 80
  # PUSHER_WS_PORT: 80
  # PUSHER_WSS_PORT: 443
  # PUSHER_ENCRYPTED: true
  # twilio setting
  # --------------------------------------------------------------
  # https://github.com/twilio/twilio-ruby
  #
  TWILIO_NUMBER: +13477516203
  TWILIO_SID: ACced22b6883e1b392b2e28a627b5f0c6a
  TWILIO_TOKEN: ca249f630529c46d5a05ef94a741e24a

  SMSAUTHKEY: 188737AzwsuMr0F5a3893b2
  SENDER: Exchange
  ROUTE: 4
  COUNTRY: 0
  # Third party auth

  # Weibo
  # --------------------------------------------------------------
  WEIBO_AUTH: on # on/off
  WEIBO_KEY: "3820920586"
  WEIBO_SECRET: 2d6174dc698e86860c75d75b1e8a01c8
  
  AUTHY_API_KEY: ZcHNkcP944q4zbFDFkrv2fNXi5PT5C5G
  AUTHY_API_URI: 'https://api.authy.com/'
  
  # chat setting
  # --------------------------------------------------------------
  # Do you want chat feature in your exchange ?
  # send mail to community@myexchangepea.com

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
