- id: 100
  key: bank
  currency: eur
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelBank
- id: 200
  key: satoshi
  currency: btc
  fixed: 12
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 400
  key: ether
  currency: eth
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 12
  fee: 0.0005
  type: WithdrawChannelEthereum
- id: 600
  key: litecoin 
  currency: ltc
  fixed: 12
  fee: 0.0005
  inuse: true
  type: WithdrawChannelLitecoin
- id: 800
  key: dashcoin 
  currency: dsh
  fixed: 12
  fee: 0.0005
  inuse: true
  type: WithdrawChannelDashcoin
- id: 1000
  key: zcash 
  currency: zec
  fixed: 12
  fee: 0.0005
  inuse: true
  type: WithdrawChannelZcash
- id: 1200
  key: ripple 
  currency: xrp
  fixed: 12
  fee: 0.0005
  inuse: true
  type: WithdrawChannelRipple
- id: 1400
  key: peercoin 
  currency: ppc
  fixed: 12
  fee: 0.0005
  inuse: true
  type: WithdrawChannelPeercoin
- id: 1600
  key: namecoin 
  currency: nmc
  fixed: 12
  fee: 0.0005
  inuse: true
  type: WithdrawChannelNamecoin
- id: 1800
  key: monero 
  currency: xmr
  fixed: 12
  fee: 0.0005
  inuse: true
  type: WithdrawChannelMonero